service: omie-harbor
frameworkVersion: '3'
useDotenv: true
configValidationMode: error
deprecationNotificationMode: error

provider:
  name: aws
  runtime: nodejs20.x
  stage: ${opt:stage, 'dev'}
  region: ${self:custom.service.region.${sls:stage}}
  stackName: ${self:custom.service.name}
  apiName: ${self:custom.service.name}
  memorySize: 128
  timeout: 30
  logRetentionInDays: 7
  deploymentPrefix: ''
  deploymentBucket:
    name: ${aws:accountId}-serverless
    maxPreviousDeploymentArtifacts: 5
  versionFunctions: false
  environment: ${file(./serverless/environment.yml)}
  endpointType: EDGE
  apiGateway:
    apiKeySourceType: HEADER
    apiKeys:
      - name: ${self:custom.service.name}
        value: ${env:API_KEY, param:apiKey}
        enabled: true
  stackTags:
    service: ${self:service}
    stage: ${sls:stage}
  tags:
    service: ${self:service}
    stage: ${sls:stage}

package:
  excludeDevDependencies: true
  individually: true
  patterns:
    - '!**'
    - 'package.json'
    - 'package-lock.json'
    - 'node_modules/**'
    - 'src/**'
    - '!src/functions/**'
    - '!src/shared/**'

plugins:
  # - serverless-domain-manager
  - serverless-iam-roles-per-function
  - serverless-apigateway-service-proxy
  - serverless-offline

params: ${file(./serverless/params.yml)}

custom: ${file(./serverless/custom.yml)}

functions: ${file(./serverless/functions.yml)}

resources: ${file(./serverless/resources.yml)}
