Resources:

  IngestionQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: ${self:custom.basename}-ingestion-queue.fifo
      FifoQueue: true
      ContentBasedDeduplication: true
      DeduplicationScope: queue
      MessageRetentionPeriod: 60 # 1min
      ReceiveMessageWaitTimeSeconds: 0
      VisibilityTimeout: ${self:functions.ingestionPerformer.timeout}
  
  DataExportQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: ${self:custom.basename}-dataExport-queue.fifo
      FifoQueue: true
      ContentBasedDeduplication: true
      DeduplicationScope: queue
      MessageRetentionPeriod: 60 # 1min
      ReceiveMessageWaitTimeSeconds: 0
      VisibilityTimeout: ${self:functions.dataExport.timeout}

  DataExportBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: ${self:custom.basename}-data-export

Outputs:
  RestApiUrl:
    Value: { 'Fn::Join': [ '', [ 'https://', { 'Ref' : 'ApiGatewayRestApi' }, '.execute-api.${self:provider.region}.amazonaws.com/${self:provider.stage}' ] ] }
    Export:
      Name: ${self:custom.basename}:RestApiUrl
  ApiKey:
    Value: ${self:custom.appApiKey.${self:provider.stage}}
    Export:
      Name: ${self:custom.basename}:ApiKey
  IngestionQueueArn:
    Value: !GetAtt IngestionQueue.Arn
    Export:
      Name: ${self:custom.basename}:IngestionQueueArn
  IngestionQueueUrl:
    Value: !Ref IngestionQueue
    Export:
      Name: ${self:custom.basename}:IngestionQueueUrl
  DataExportBucketArn:
    Value: !GetAtt DataExportBucket.Arn
    Export:
      Name: ${self:custom.basename}:DataExportBucketArn
  DataExportBucketName:
    Value: !Ref DataExportBucket
    Export:
      Name: ${self:custom.basename}:DataExportBucketName