Resources:

  IngestionQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: ${self:custom.basename}-ingestion-queue.fifo
      FifoQueue: true
      ContentBasedDeduplication: true
      DeduplicationScope: queue
      MessageRetentionPeriod: 60 # 1min
      ReceiveMessageWaitTimeSeconds: 20
      VisibilityTimeout: ${self:functions.ingestionPerformer.timeout}

  DataProcessingQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: ${self:custom.basename}-dataProcessing-queue.fifo
      FifoQueue: true
      ContentBasedDeduplication: true
      DeduplicationScope: queue
      MessageRetentionPeriod: 60 # 1min
      ReceiveMessageWaitTimeSeconds: 20
      VisibilityTimeout: ${self:functions.dataProcessing.timeout}

  DataExportQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: ${self:custom.basename}-dataExport-queue.fifo
      FifoQueue: true
      ContentBasedDeduplication: true
      DeduplicationScope: queue
      MessageRetentionPeriod: 60 # 1min
      ReceiveMessageWaitTimeSeconds: 20
      VisibilityTimeout: ${self:functions.dataExport.timeout}

  DataExportBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: ${self:custom.basename}-data-export-bucket

Outputs:
  IngestionQueueArn:
    Value: !GetAtt IngestionQueue.Arn
    Export:
      Name: ${self:custom.basename}:IngestionQueueArn
  IngestionQueueUrl:
    Value: !Ref IngestionQueue
    Export:
      Name: ${self:custom.basename}:IngestionQueueUrl
  DataProcessingQueueArn:
    Value: !GetAtt DataProcessingQueue.Arn
    Export:
      Name: ${self:custom.basename}:DataProcessingQueueArn
  DataProcessingQueueUrl:
    Value: !Ref DataProcessingQueue
    Export:
      Name: ${self:custom.basename}:DataProcessingQueueUrl
  DataExportBucketArn:
    Value: !GetAtt DataExportBucket.Arn
    Export:
      Name: ${self:custom.basename}:DataExportBucketArn
  DataExportBucketName:
    Value: !Ref DataExportBucket
    Export:
      Name: ${self:custom.basename}:DataExportBucketName