const USER_ROLE = {
  SUPER: 'SUPER',
  ADMIN: 'ADMIN',
  DEFAULT: 'DEFAULT',
  CUSTOMER_ADMIN: 'CUSTOMER_ADMIN',
  CUSTOMER_DEFAULT: 'CUSTOMER_DEFAULT'
}

const OMIE_WEBHOOK_EVENT_TYPES = [
  'OrdemServico.Excluida'
]

module.exports = {
  USER_ROLE,
  OMIE_WEBHOOK_EVENT_TYPES
}
